name: global_snowmelt_runoff_onset
channels:
  - conda-forge
  - defaults
dependencies:
  - odc-stac>=0.4
  - rioxarray
  - xarray
  - bottleneck
  - dask
  - netCDF4
  - h5netcdf
  - fsspec
  - cftime
  - pooch
  - scipy
  - zarr #>=3
  - pystac
  - pystac-client
  - coiled
  - geodatasets
  - adlfs
  - easysnowdata
  - flox
  - geopandas
  - shapely
  - pyproj
  - pip

  - pip:
      #- xee==0.0.15
      #- "--editable=git+https://github.com/egagli/easysnowdata.git#egg=easysnowdata"
      - "--editable=./"
