[workspace]
name = "global-snowmelt-runoff-onset"
version = "0.1.0"
description = "Global snowmelt runoff onset dataset and processing pipeline"
authors = ["Eric Gagliano <egagli@uw.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.12"
odc-stac = ">=0.5.3"
rioxarray = "*"
xarray = "*"
bottleneck = "*"
dask = "*"
netcdf4 = "*"
h5netcdf = "*"
fsspec = "*"
cftime = "*"
pooch = "*"
scipy = "*"
zarr = "*"
pystac = "*"
pystac-client = "*"
geodatasets = "*"
adlfs = "*"
easysnowdata = ">=0.0.24,<0.0.25"
flox = "*"
geopandas = "*"
shapely = "*"
pyproj = "*"
geocube = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
requests = "*"
planetary-computer = "*"
odc-geo = "*"
azure-storage-blob = "*"
ipywidgets = "*"
seaborn = ">=0.13.2,<0.14"
cartopy = ">=0.25.0,<0.26"
matplotlib-scalebar = ">=0.9.0,<0.10"
numba = ">=0.66.0,<0.67"
icechunk = ">=2.0.0,<3"


[pypi-dependencies]
global-snowmelt-runoff-onset = { path = ".", editable = true }

[feature.dev.dependencies]
jupyterlab = "*"
matplotlib = "*"
ipywidgets = "*"
contextily = "*"
folium = "*"
rasterio = "*"
earthengine-api = "*"
exactextract = "*"

[feature.ci.dependencies]
python = "3.12.*"
numpy = "*"
pandas = "*"
xarray = "*"
dask = "*"
geopandas = "*"
rasterio = "*"
tqdm = "*"
requests = "*"
pystac-client = "*"
planetary-computer = "*"
odc-stac = ">=0.5.3"
odc-geo = "*"
zarr = "*"
azure-storage-blob = "*"
adlfs = "*"
shapely = "*"
easysnowdata = ">=0.0.24,<0.0.25"
flox = "*"
icechunk = ">=2.0.0,<3"

[environments]
default = { features = ["dev"] }
ci = { features = ["ci"], solve-group = "ci" }

[tasks]
lab = "jupyter lab"
setup-kernel = "python ~/setup_kernel.py"
