name: Consolidate Tile Results

on:
  workflow_dispatch:
    inputs:
      days_back:
        description: 'How many days back to look for artifacts'
        required: false
        default: '7'
        type: string
      config_version:
        description: 'Config version (e.g., v9)'
        required: false
        default: 'v9'
        type: string

env:
  AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}

permissions:
  contents: write
  actions: read  # Need this to download artifacts

jobs:
  consolidate-results:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment_github_actions.yml
        activate-environment: global_snowmelt_runoff_onset_actions
        auto-activate-base: false
        
    - name: Consolidate artifacts using Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash -l {0}
      run: |
        python processing/scripts/consolidate_artifacts.py github \
          --repo "${{ github.repository }}" \
          --token "${{ secrets.GITHUB_TOKEN }}" \
          --days-back "${{ github.event.inputs.days_back || '7' }}" \
          --config-version "${{ github.event.inputs.config_version || 'v9' }}"
        
    - name: Commit consolidated results
      run: |
        # Check if there are changes to commit
        if [[ -n "$(git status --porcelain processing/tile_data/tile_results_*.csv)" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Consolidation)"
          
          git add processing/tile_data/tile_results_*.csv
          git commit -m "🔄 Consolidated tile results from artifacts"
          
          # Push with retry logic
          for i in {1..3}; do
            if git push; then
              echo "✅ Successfully pushed consolidated results"
              break
            else
              echo "⚠️  Push failed (attempt $i/3), retrying in 5 seconds..."
              sleep 5
              git pull --rebase origin main || true
            fi
            
            if [ $i -eq 3 ]; then
              echo "❌ Failed to push after 3 attempts"
              exit 1
            fi
          done
        else
          echo "✅ No changes to commit - all artifacts already consolidated"
        fi
