name: Process Tile Batch

on:
  workflow_dispatch:
    inputs:
      which_tiles_to_process:
        description: 'Which tiles to process (failed/unprocessed/all)'
        required: false
        default: 'failed'
        type: choice
        options:
        - failed
        - unprocessed
        - all
      how_many:
        description: 'How many tiles to process (max)'
        required: false
        default: '10'
        type: string
      config_file:
        description: 'Config file to use (e.g., global_config_v9.txt)'
        required: false
        default: 'global_config_v9.txt'
        type: string

env:
  AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}

permissions:
  contents: write

jobs:
  generate-tile-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-tiles.outputs.matrix }}
      tile-count: ${{ steps.get-tiles.outputs.count }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        miniforge-variant: Miniforge3
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: global_snowmelt_runoff_onset_actions
        environment-file: environment_github_actions.yml
        
    - name: Get tiles for batch processing
      id: get-tiles
      shell: bash -l {0}
      run: |
        MATRIX=$(python scripts/get_tiles_for_batch.py \
          --config-file ${{ github.event.inputs.config_file }} \
          --which-tiles ${{ github.event.inputs.which_tiles_to_process }} \
          --how-many ${{ github.event.inputs.how_many }} \
          --output-format json)
        echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
        
        COUNT=$(python scripts/get_tiles_for_batch.py \
          --config-file ${{ github.event.inputs.config_file }} \
          --which-tiles ${{ github.event.inputs.which_tiles_to_process }} \
          --how-many ${{ github.event.inputs.how_many }} \
          --output-format count)
        echo "count=$COUNT" >> $GITHUB_OUTPUT

  process-tiles:
    needs: generate-tile-matrix
    if: fromJson(needs.generate-tile-matrix.outputs.tile-count) > 0
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        tile: ${{ fromJson(needs.generate-tile-matrix.outputs.matrix) }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        miniforge-variant: Miniforge3
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: global_snowmelt_runoff_onset_actions
        environment-file: environment_github_actions.yml
        
    - name: Process tile
      shell: bash -l {0}
      run: |
        python scripts/process_single_tile.py \
          --tile-row ${{ matrix.tile.row }} \
          --tile-col ${{ matrix.tile.col }} \
          --config-file ${{ github.event.inputs.config_file }}
          
    - name: Create failure record if processing crashed
      if: always()
      shell: bash -l {0}
      run: |
        CONFIG_FILE="${{ github.event.inputs.config_file }}"
        VERSION=$(echo "$CONFIG_FILE" | sed 's/.*v\([0-9]*\).*/v\1/')
        
        if [ ! -f "processing/tile_data/github_workflow_results/tile_${{ matrix.tile.row }}_${{ matrix.tile.col }}_${VERSION}.csv" ]; then
          python -c "
        import pandas as pd
        from pathlib import Path
        
        output_dir = Path('processing/tile_data/github_workflow_results')
        output_dir.mkdir(parents=True, exist_ok=True)
        
        csv_file = output_dir / 'tile_${{ matrix.tile.row }}_${{ matrix.tile.col }}_${VERSION}.csv'
        
        if not csv_file.exists():
            failure_data = {
                'row': [${{ matrix.tile.row }}],
                'col': [${{ matrix.tile.col }}],
                'success': [False],
                'total_time': [0],
                'error_messages': ['Batch workflow crashed - no CSV created'],
                'tr_2015': [None], 'tr_2016': [None], 'tr_2017': [None], 'tr_2018': [None], 'tr_2019': [None],
                'tr_2020': [None], 'tr_2021': [None], 'tr_2022': [None], 'tr_2023': [None], 'tr_2024': [None],
                'pix_ct_2015': [None], 'pix_ct_2016': [None], 'pix_ct_2017': [None], 'pix_ct_2018': [None], 'pix_ct_2019': [None],
                'pix_ct_2020': [None], 'pix_ct_2021': [None], 'pix_ct_2022': [None], 'pix_ct_2023': [None], 'pix_ct_2024': [None]
            }
            
            df = pd.DataFrame(failure_data)
            df.to_csv(csv_file, index=False)
            print(f'Created failure record: {csv_file}')
        "
        fi
        
    - name: Commit tile results
      if: always()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action (Batch)"
        
        if ! git diff --quiet processing/tile_data/; then
          git add processing/tile_data/
          
          for i in {1..5}; do
            git pull origin main --no-rebase || echo "Pull failed, continuing..."
            
            if ! git diff --staged --quiet; then
              git commit -m "Add batch tile (${{ matrix.tile.row }}, ${{ matrix.tile.col }}) results" || echo "Commit failed, may already be committed"
            fi
            
            if git push; then
              echo "Successfully pushed tile results"
              break
            else
              echo "Push failed (attempt $i/5), waiting before retry..."
              sleep $((i * 2))
              git add processing/tile_data/
            fi
            
            if [ $i -eq 5 ]; then
              echo "Failed to push after 5 attempts"
              exit 1
            fi
          done
        else
          echo "No changes to commit"
        fi
