name: Process Single Tile

on:
  workflow_dispatch:
    inputs:
      tile_row:
        description: 'Tile row coordinate'
        required: true
        type: number
      tile_col:
        description: 'Tile column coordinate'
        required: true
        type: number
      config_file:
        description: 'Config file to use (e.g., global_config_v9.txt)'
        required: false
        default: 'global_config_v9.txt'
        type: string

env:
  AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}

jobs:
  process-tile:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        miniforge-variant: Miniforge3
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: global_snowmelt_runoff_onset_actions
        environment-file: environment_github_actions.yml
        
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .
        
    - name: Process tile
      shell: bash -l {0}
      run: |
        python processing/scripts/process_single_tile.py \
          --tile-row ${{ github.event.inputs.tile_row }} \
          --tile-col ${{ github.event.inputs.tile_col }} \
          --config-file ${{ github.event.inputs.config_file }}
          
    - name: Upload tile result as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tile-result-${{ github.event.inputs.tile_row }}-${{ github.event.inputs.tile_col }}
        path: processing/tile_data/github_workflow_results/tile_${{ github.event.inputs.tile_row }}_${{ github.event.inputs.tile_col }}_*.csv
        retention-days: 30
        if-no-files-found: ignore
