name: Process Single Tile

on:
  workflow_dispatch:
    inputs:
      tile_row:
        description: 'Tile row coordinate'
        required: true
        type: number
      tile_col:
        description: 'Tile column coordinate'
        required: true
        type: number
      config_file:
        description: 'Config file to use (e.g., global_config_v9.txt)'
        required: false
        default: 'global_config_v9.txt'
        type: string

env:
  AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}

permissions:
  contents: write

jobs:
  process-tile:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        miniforge-variant: Miniforge3
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: global_snowmelt_runoff_onset_actions
        environment-file: environment_github_actions.yml
        
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .
        
    - name: Process tile
      shell: bash -l {0}
      run: |
        python processing/scripts/process_single_tile.py \
          --tile-row ${{ github.event.inputs.tile_row }} \
          --tile-col ${{ github.event.inputs.tile_col }} \
          --config-file ${{ github.event.inputs.config_file }}
          
    - name: Commit tile results
      if: always()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [[ -n "$(git status --porcelain processing/tile_data/)" ]]; then
          git add processing/tile_data/
          
          for i in {1..5}; do
            git pull origin main --no-rebase || echo "Pull failed, continuing..."
            
            if ! git diff --staged --quiet; then
              git commit -m "Add tile (${{ github.event.inputs.tile_row }}, ${{ github.event.inputs.tile_col }}) results" || echo "Commit failed, may already be committed"
            fi
            
            if git push; then
              echo "Successfully pushed tile results"
              break
            else
              echo "Push failed (attempt $i/5), waiting before retry..."
              sleep $((i * 2))
              git add processing/tile_data/
            fi
            
            if [ $i -eq 5 ]; then
              echo "Failed to push after 5 attempts"
              exit 1
            fi
          done
        else
          echo "No changes to commit"
        fi
